#ifndef LUTS_H
#define LUTS_H

#include <QtGui/QColor>

struct tileLUTEntry {
   bool hasTexCoords;
   bool isBlocking;
   QColor color;
   QString name;
};

tileLUTEntry tileLUT(int n) {
   switch (n) {
   case   0: return (tileLUTEntry){false, false, QColor(), ""};
   case   1: return (tileLUTEntry){false, false, QColor(), ""};
   case   2: return (tileLUTEntry){false, false, QColor(), ""};
   case   3: return (tileLUTEntry){true , false, QColor(), ""};
   case   4: return (tileLUTEntry){true , false, QColor(), ""};
   case   5: return (tileLUTEntry){true , false, QColor(), ""};
   case   6: return (tileLUTEntry){false, false, QColor(), ""};
   case   7: return (tileLUTEntry){false, false, QColor(), ""};
   case   8: return (tileLUTEntry){false, false, QColor(), ""};
   case   9: return (tileLUTEntry){false, false, QColor(), ""};
   case  10: return (tileLUTEntry){true , false, QColor(), ""};
   case  11: return (tileLUTEntry){true , false, QColor(), ""};
   case  12: return (tileLUTEntry){true , false, QColor(), ""};
   case  13: return (tileLUTEntry){true , false, QColor(), ""};
   case  14: return (tileLUTEntry){true , false, QColor(), ""};
   case  15: return (tileLUTEntry){true , false, QColor(), ""};
   case  16: return (tileLUTEntry){true , false, QColor(), ""};
   case  17: return (tileLUTEntry){true , false, QColor(), ""};
   case  18: return (tileLUTEntry){true , false, QColor(), ""};
   case  19: return (tileLUTEntry){true , false, QColor(), ""};
   case  20: return (tileLUTEntry){true , false, QColor(), ""};
   case  21: return (tileLUTEntry){true , false, QColor(), ""};
   case  22: return (tileLUTEntry){false, false, QColor(), ""};
   case  23: return (tileLUTEntry){false, false, QColor(), ""};
   case  24: return (tileLUTEntry){true , false, QColor(), ""};
   case  25: return (tileLUTEntry){false, false, QColor(), ""};
   case  26: return (tileLUTEntry){true , false, QColor(), ""};
   case  27: return (tileLUTEntry){true , false, QColor(), ""};
   case  28: return (tileLUTEntry){true , false, QColor(), ""};
   case  29: return (tileLUTEntry){true , false, QColor(), ""};
   case  30: return (tileLUTEntry){false, false, QColor(), ""};
   case  31: return (tileLUTEntry){true , false, QColor(), ""};
   case  32: return (tileLUTEntry){false, false, QColor(), ""};
   case  33: return (tileLUTEntry){true , false, QColor(), ""};
   case  34: return (tileLUTEntry){true , false, QColor(), ""};
   case  35: return (tileLUTEntry){true , false, QColor(), ""};
   case  36: return (tileLUTEntry){true , false, QColor(), ""};
   case  37: return (tileLUTEntry){false, false, QColor(), ""};
   case  38: return (tileLUTEntry){false, false, QColor(), ""};
   case  39: return (tileLUTEntry){false, false, QColor(), ""};
   case  40: return (tileLUTEntry){false, false, QColor(), ""};
   case  41: return (tileLUTEntry){false, false, QColor(), ""};
   case  42: return (tileLUTEntry){true , false, QColor(), ""};
   case  43: return (tileLUTEntry){false, false, QColor(), ""};
   case  44: return (tileLUTEntry){false, false, QColor(), ""};
   case  45: return (tileLUTEntry){false, false, QColor(), ""};
   case  46: return (tileLUTEntry){false, false, QColor(), ""};
   case  47: return (tileLUTEntry){false, false, QColor(), ""};
   case  48: return (tileLUTEntry){false, false, QColor(), ""};
   case  49: return (tileLUTEntry){false, false, QColor(), ""};
   case  50: return (tileLUTEntry){true , false, QColor(), ""};
   case  51: return (tileLUTEntry){false, false, QColor(), ""};
   case  52: return (tileLUTEntry){false, false, QColor(), ""};
   case  53: return (tileLUTEntry){false, false, QColor(), ""};
   case  54: return (tileLUTEntry){false, false, QColor(), ""};
   case  55: return (tileLUTEntry){true , false, QColor(), ""};
   case  56: return (tileLUTEntry){false, false, QColor(), ""};
   case  57: return (tileLUTEntry){false, false, QColor(), ""};
   case  58: return (tileLUTEntry){false, false, QColor(), ""};
   case  59: return (tileLUTEntry){false, false, QColor(), ""};
   case  60: return (tileLUTEntry){false, false, QColor(), ""};
   case  61: return (tileLUTEntry){true , false, QColor(), ""};
   case  62: return (tileLUTEntry){false, false, QColor(), ""};
   case  63: return (tileLUTEntry){false, false, QColor(), ""};
   case  64: return (tileLUTEntry){false, false, QColor(), ""};
   case  65: return (tileLUTEntry){false, false, QColor(), ""};
   case  66: return (tileLUTEntry){false, false, QColor(), ""};
   case  67: return (tileLUTEntry){false, false, QColor(), ""};
   case  68: return (tileLUTEntry){false, false, QColor(), ""};
   case  69: return (tileLUTEntry){false, false, QColor(), ""};
   case  70: return (tileLUTEntry){false, false, QColor(), ""};
   case  71: return (tileLUTEntry){true , false, QColor(), ""};
   case  72: return (tileLUTEntry){true , false, QColor(), ""};
   case  73: return (tileLUTEntry){true , false, QColor(), ""};
   case  74: return (tileLUTEntry){true , false, QColor(), ""};
   case  75: return (tileLUTEntry){false, false, QColor(), ""};
   case  76: return (tileLUTEntry){false, false, QColor(), ""};
   case  77: return (tileLUTEntry){true , false, QColor(), ""};
   case  78: return (tileLUTEntry){true , false, QColor(), ""};
   case  79: return (tileLUTEntry){true , false, QColor(), ""};
   case  80: return (tileLUTEntry){false, false, QColor(), ""};
   case  81: return (tileLUTEntry){true , false, QColor(), ""};
   case  82: return (tileLUTEntry){true , false, QColor(), ""};
   case  83: return (tileLUTEntry){true , false, QColor(), ""};
   case  84: return (tileLUTEntry){true , false, QColor(), ""};
   case  85: return (tileLUTEntry){true , false, QColor(), ""};
   case  86: return (tileLUTEntry){true , false, QColor(), ""};
   case  87: return (tileLUTEntry){true , false, QColor(), ""};
   case  88: return (tileLUTEntry){true , false, QColor(), ""};
   case  89: return (tileLUTEntry){true , false, QColor(), ""};
   case  90: return (tileLUTEntry){true , false, QColor(), ""};
   case  91: return (tileLUTEntry){true , false, QColor(), ""};
   case  92: return (tileLUTEntry){true , false, QColor(), ""};
   case  93: return (tileLUTEntry){true , false, QColor(), ""};
   case  94: return (tileLUTEntry){true , false, QColor(), ""};
   case  95: return (tileLUTEntry){true , false, QColor(), ""};
   case  96: return (tileLUTEntry){true , false, QColor(), ""};
   case  97: return (tileLUTEntry){true , false, QColor(), ""};
   case  98: return (tileLUTEntry){true , false, QColor(), ""};
   case  99: return (tileLUTEntry){true , false, QColor(), ""};
   case 100: return (tileLUTEntry){true , false, QColor(), ""};
   case 101: return (tileLUTEntry){true , false, QColor(), ""};
   case 102: return (tileLUTEntry){true , false, QColor(), ""};
   case 103: return (tileLUTEntry){true , false, QColor(), ""};
   case 104: return (tileLUTEntry){true , false, QColor(), ""};
   case 105: return (tileLUTEntry){true , false, QColor(), ""};
   case 106: return (tileLUTEntry){true , false, QColor(), ""};
   case 107: return (tileLUTEntry){false, false, QColor(), ""};
   case 108: return (tileLUTEntry){false, false, QColor(), ""};
   case 109: return (tileLUTEntry){false, false, QColor(), ""};
   case 110: return (tileLUTEntry){true , false, QColor(), ""};
   case 111: return (tileLUTEntry){false, false, QColor(), ""};
   case 112: return (tileLUTEntry){false, false, QColor(), ""};
   case 113: return (tileLUTEntry){true , false, QColor(), ""};
   case 114: return (tileLUTEntry){true , false, QColor(), ""};
   case 115: return (tileLUTEntry){false, false, QColor(), ""};
   case 116: return (tileLUTEntry){false, false, QColor(), ""};
   case 117: return (tileLUTEntry){false, false, QColor(), ""};
   case 118: return (tileLUTEntry){false, false, QColor(), ""};
   case 119: return (tileLUTEntry){false, false, QColor(), ""};
   case 120: return (tileLUTEntry){false, false, QColor(), ""};
   case 121: return (tileLUTEntry){false, false, QColor(), ""};
   case 122: return (tileLUTEntry){false, false, QColor(), ""};
   case 123: return (tileLUTEntry){false, false, QColor(), ""};
   case 124: return (tileLUTEntry){false, false, QColor(), ""};
   case 125: return (tileLUTEntry){true , false, QColor(), ""};
   case 126: return (tileLUTEntry){true , false, QColor(), ""};
   case 127: return (tileLUTEntry){false, false, QColor(), ""};
   case 128: return (tileLUTEntry){true , false, QColor(), ""};
   case 129: return (tileLUTEntry){true , false, QColor(), ""};
   case 130: return (tileLUTEntry){false, false, QColor(), ""};
   case 131: return (tileLUTEntry){false, false, QColor(), ""};
   case 132: return (tileLUTEntry){true , false, QColor(), ""};
   case 133: return (tileLUTEntry){true , false, QColor(), ""};
   case 134: return (tileLUTEntry){true , false, QColor(), ""};
   case 135: return (tileLUTEntry){true , false, QColor(), ""};
   case 136: return (tileLUTEntry){true , false, QColor(), ""};
   case 137: return (tileLUTEntry){true , false, QColor(), ""};
   case 138: return (tileLUTEntry){true , false, QColor(), ""};
   case 139: return (tileLUTEntry){true , false, QColor(), ""};
   case 140: return (tileLUTEntry){false, false, QColor(), ""};
   case 141: return (tileLUTEntry){true , false, QColor(), ""};
   case 142: return (tileLUTEntry){true , false, QColor(), ""};
   case 143: return (tileLUTEntry){true , false, QColor(), ""};
   case 144: return (tileLUTEntry){true , false, QColor(), ""};
   case 145: return (tileLUTEntry){false, false, QColor(), ""};
   case 146: return (tileLUTEntry){false, false, QColor(), ""};
   case 147: return (tileLUTEntry){false, false, QColor(), ""};
   case 148: return (tileLUTEntry){false, false, QColor(), ""};
   case 149: return (tileLUTEntry){true , false, QColor(), ""};
   case 150: return (tileLUTEntry){false, false, QColor(), ""};
   case 151: return (tileLUTEntry){false, false, QColor(), ""};
   case 152: return (tileLUTEntry){false, false, QColor(), ""};
   case 153: return (tileLUTEntry){false, false, QColor(), ""};
   case 154: return (tileLUTEntry){false, false, QColor(), ""};
   case 155: return (tileLUTEntry){false, false, QColor(), ""};
   case 156: return (tileLUTEntry){false, false, QColor(), ""};
   case 157: return (tileLUTEntry){false, false, QColor(), ""};
   case 158: return (tileLUTEntry){false, false, QColor(), ""};
   case 159: return (tileLUTEntry){false, false, QColor(), ""};
   case 160: return (tileLUTEntry){false, false, QColor(), ""};
   case 161: return (tileLUTEntry){false, false, QColor(), ""};
   case 162: return (tileLUTEntry){false, false, QColor(), ""};
   case 163: return (tileLUTEntry){false, false, QColor(), ""};
   case 164: return (tileLUTEntry){false, false, QColor(), ""};
   case 165: return (tileLUTEntry){true , false, QColor(), ""};
   case 166: return (tileLUTEntry){false, false, QColor(), ""};
   case 167: return (tileLUTEntry){false, false, QColor(), ""};
   case 168: return (tileLUTEntry){false, false, QColor(), ""};
   case 169: return (tileLUTEntry){false, false, QColor(), ""};
   case 170: return (tileLUTEntry){true , false, QColor(), ""};
   case 171: return (tileLUTEntry){true , false, QColor(), ""};
   case 172: return (tileLUTEntry){true , false, QColor(), ""};
   case 173: return (tileLUTEntry){true , false, QColor(), ""};
   case 174: return (tileLUTEntry){true , false, QColor(), ""};
   case 175: return (tileLUTEntry){false, false, QColor(), ""};
   case 176: return (tileLUTEntry){false, false, QColor(), ""};
   case 177: return (tileLUTEntry){false, false, QColor(), ""};
   case 178: return (tileLUTEntry){true , false, QColor(), ""};
   case 179: return (tileLUTEntry){false, false, QColor(), ""};
   case 180: return (tileLUTEntry){false, false, QColor(), ""};
   case 181: return (tileLUTEntry){false, false, QColor(), ""};
   case 182: return (tileLUTEntry){false, false, QColor(), ""};
   case 183: return (tileLUTEntry){false, false, QColor(), ""};
   case 184: return (tileLUTEntry){true , false, QColor(), ""};
   case 185: return (tileLUTEntry){true , false, QColor(), ""};
   case 186: return (tileLUTEntry){true , false, QColor(), ""};
   case 187: return (tileLUTEntry){true , false, QColor(), ""};
   case 188: return (tileLUTEntry){false, false, QColor(), ""};
   case 189: return (tileLUTEntry){false, false, QColor(), ""};
   case 190: return (tileLUTEntry){false, false, QColor(), ""};
   case 191: return (tileLUTEntry){false, false, QColor(), ""};
   case 192: return (tileLUTEntry){false, false, QColor(), ""};
   case 193: return (tileLUTEntry){false, false, QColor(), ""};
   case 194: return (tileLUTEntry){false, false, QColor(), ""};
   case 195: return (tileLUTEntry){false, false, QColor(), ""};
   case 196: return (tileLUTEntry){false, false, QColor(), ""};
   case 197: return (tileLUTEntry){false, false, QColor(), ""};
   case 198: return (tileLUTEntry){false, false, QColor(), ""};
   case 199: return (tileLUTEntry){false, false, QColor(), ""};
   case 200: return (tileLUTEntry){false, false, QColor(), ""};
   case 201: return (tileLUTEntry){true , false, QColor(), ""};
   case 202: return (tileLUTEntry){false, false, QColor(), ""};
   case 203: return (tileLUTEntry){false, false, QColor(), ""};
   case 204: return (tileLUTEntry){false, false, QColor(), ""};
   case 205: return (tileLUTEntry){false, false, QColor(), ""};
   case 206: return (tileLUTEntry){false, false, QColor(), ""};
   case 207: return (tileLUTEntry){true , false, QColor(), ""};
   case 208: return (tileLUTEntry){false, false, QColor(), ""};
   case 209: return (tileLUTEntry){true , false, QColor(), ""};
   case 210: return (tileLUTEntry){true , false, QColor(), ""};
   case 211: return (tileLUTEntry){false, false, QColor(), ""};
   case 212: return (tileLUTEntry){true , false, QColor(), ""};
   case 213: return (tileLUTEntry){false, false, QColor(), ""};
   case 214: return (tileLUTEntry){false, false, QColor(), ""};
   case 215: return (tileLUTEntry){true , false, QColor(), ""};
   case 216: return (tileLUTEntry){true , false, QColor(), ""};
   case 217: return (tileLUTEntry){true , false, QColor(), ""};
   case 218: return (tileLUTEntry){true , false, QColor(), ""};
   case 219: return (tileLUTEntry){true , false, QColor(), ""};
   case 220: return (tileLUTEntry){true , false, QColor(), ""};
   case 221: return (tileLUTEntry){false, false, QColor(), ""};
   case 222: return (tileLUTEntry){false, false, QColor(), ""};
   case 223: return (tileLUTEntry){false, false, QColor(), ""};
   case 224: return (tileLUTEntry){false, false, QColor(), ""};
   case 225: return (tileLUTEntry){false, false, QColor(), ""};
   case 226: return (tileLUTEntry){false, false, QColor(), ""};
   case 227: return (tileLUTEntry){true , false, QColor(), ""};
   case 228: return (tileLUTEntry){true , false, QColor(), ""};
   case 229: return (tileLUTEntry){false, false, QColor(), ""};
   case 230: return (tileLUTEntry){false, false, QColor(), ""};
   case 231: return (tileLUTEntry){true , false, QColor(), ""};
   case 232: return (tileLUTEntry){false, false, QColor(), ""};
   case 233: return (tileLUTEntry){true , false, QColor(), ""};
   case 234: return (tileLUTEntry){false, false, QColor(), ""};
   case 235: return (tileLUTEntry){true , false, QColor(), ""};
   case 236: return (tileLUTEntry){true , false, QColor(), ""};
   case 237: return (tileLUTEntry){true , false, QColor(), ""};
   case 238: return (tileLUTEntry){true , false, QColor(), ""};
   case 239: return (tileLUTEntry){true , false, QColor(), ""};
   case 240: return (tileLUTEntry){true , false, QColor(), ""};
   case 241: return (tileLUTEntry){true , false, QColor(), ""};
   case 242: return (tileLUTEntry){true , false, QColor(), ""};
   case 243: return (tileLUTEntry){true , false, QColor(), ""};
   case 244: return (tileLUTEntry){true , false, QColor(), ""};
   case 245: return (tileLUTEntry){true , false, QColor(), ""};
   case 246: return (tileLUTEntry){true , false, QColor(), ""};
   case 247: return (tileLUTEntry){true , false, QColor(), ""};
   case 248: return (tileLUTEntry){false, false, QColor(), ""};
   case 249: return (tileLUTEntry){false, false, QColor(), ""};
   case 250: return (tileLUTEntry){false, false, QColor(), ""};
   case 251: return (tileLUTEntry){false, false, QColor(), ""};
   case 252: return (tileLUTEntry){false, false, QColor(), ""};
   case 253: return (tileLUTEntry){false, false, QColor(), ""};
   case 254: return (tileLUTEntry){true , false, QColor(), ""};
   default : return (tileLUTEntry){false, false, QColor(), QString()};
   }
}

#endif // LUTS_H
